exports.seed = function(knex) {
  return knex("flights").then(function() {
    return knex("flights").insert([
      {
        id: 1,
        departure_date: "departuredate1",
        departure_airport_name: "departureairport1",
        departure_airport_address: "departureairportaddress1",
        departure_airport_phone: "departureairportphone1",
        departure_ticket_number: "departureticketnum1",
        departure_flight_number: "departureflightnum1",
        departure_terminal: "departureterminal1",
        departure_gate: "departuregate1",
        departure_flight_note: "departureflightnote1",
        arrival_date: "arrivaldate1",
        arrival_airport_name: "arrivalairportname1",
        arrival_airport_address: "arrivalairportadd1",
        arrival_airport_phone: "arrivalairportphone1",
        arrival_ticket_number: "arrivalticketnum1",
        arrival_flight_number: "arrivalflightnum1",
        arrival_terminal: "arrivalterminal1",
        arrival_gate: "arrivalgate1",
        arrival_flight_note: "arrivalflightnote1",
        total_flight_cost: "totalflightcost1",
        flight_combo_upvote: 1
      },
      {
        id: 2,
        departure_date: "departuredate2",
        departure_airport_name: "departureairport2",
        departure_airport_address: "departureairportaddress2",
        departure_airport_phone: "departureairportphone2",
        departure_ticket_number: "departureticketnum2",
        departure_flight_number: "departureflightnum2",
        departure_terminal: "departureterminal2",
        departure_gate: "departuregate2",
        departure_flight_note: "departureflightnote2",
        arrival_date: "arrivaldate2",
        arrival_airport_name: "arrivalairportname2",
        arrival_airport_address: "arrivalairportadd2",
        arrival_airport_phone: "arrivalairportphone2",
        arrival_ticket_number: "arrivalticketnum2",
        arrival_flight_number: "arrivalflightnum2",
        arrival_terminal: "arrivalterminal2",
        arrival_gate: "arrivalgate2",
        arrival_flight_note: "arrivalflightnote2",
        total_flight_cost: "totalflightcost2",
        flight_combo_upvote: 2
      },
      {
        id: 3,
        departure_date: "departuredate3",
        departure_airport_name: "departureairport3",
        departure_airport_address: "departureairportaddress3",
        departure_airport_phone: "departureairportphone3",
        departure_ticket_number: "departureticketnum3",
        departure_flight_number: "departureflightnum3",
        departure_terminal: "departureterminal3",
        departure_gate: "departuregate3",
        departure_flight_note: "departureflightnote3",
        arrival_date: "arrivaldate3",
        arrival_airport_name: "arrivalairportname3",
        arrival_airport_address: "arrivalairportadd3",
        arrival_airport_phone: "arrivalairportphone3",
        arrival_ticket_number: "arrivalticketnum3",
        arrival_flight_number: "arrivalflightnum3",
        arrival_terminal: "arrivalterminal3",
        arrival_gate: "arrivalgate3",
        arrival_flight_note: "arrivalflightnote3",
        total_flight_cost: "totalflightcost3",
        flight_combo_upvote: 3
      }
    ]);
  });
};
